export let ins: any[] = [
  {
    name: 'Fatima Zahra Benabdeljalil',
    email: 'fatima.zahra@example.com',
    password: 'motdepasse123',
    isValid: true,
  },
  {
    name: 'Mohammed Amine Chaoui',
    email: 'mohammed.amine@example.com',
    password: 'mdpsecure',
    isValid: true,
  },
  {
    name: 'Amina El Khattabi',
    email: 'amina.el@example.com',
    password: 'motdepasse123',
    isValid: true,
  },
  {
    name: 'Youssef El Fassi',
    email: 'youssef.el@example.com',
    password: 'P@ssw0rd',
    isValid: true,
  },
  {
    name: 'Sanaa Aboussir',
    email: 'sanaa.a@example.com',
    password: 'monmotdepasse',
    isValid: true,
  },
  {
    name: 'Ahmed Ben Salah',
    email: 'ahmed.ben@example.com',
    password: 'Pa$$w0rd',
    isValid: true,
  },
  {
    name: 'Nadia El Harrak',
    email: 'nadia.el@example.com',
    password: 'mdpsecure123',
    isValid: true,
  },
  {
    name: 'Hicham Rami',
    email: 'hicham.r@example.com',
    password: '1SecurePassword',
    isValid: false,
  },
  {
    name: 'Leila Ezzahraoui',
    email: 'leila.ez@example.com',
    password: 'MonP@ssword123',
    isValid: true,
  },
  {
    name: 'Khalid Bouchama',
    email: 'khalid.b@example.com',
    password: 'motdepasse456',
    isValid: true,
  },
  {
    name: 'Nora El Alami',
    email: 'nora.e@example.com',
    password: 'SecurePwd789',
    isValid: true,
  },
  {
    name: 'Amine Berrada',
    email: 'amine.b@example.com',
    password: 'P@ssw0rd123',
    isValid: false,
  },
  {
    name: 'Houda El Kabbaj',
    email: 'houda.el@example.com',
    password: 'SecretPwd42',
    isValid: true,
  },
  {
    name: 'Mehdi Bensouda',
    email: 'mehdi.b@example.com',
    password: 'PwdSecure789',
    isValid: false,
  },
  {
    name: 'Asmaa El Amrani',
    email: 'asmaa.e@example.com',
    password: 'P@sswordSecure',
    isValid: true,
  },
  {
    name: 'Karim Benjelloun',
    email: 'karim.b@example.com',
    password: 'SecureP@ss',
    isValid: false,
  },
  {
    name: 'Nawal El Haddad',
    email: 'nawal.el@example.com',
    password: 'Secret123',
    isValid: true,
  },
  {
    name: 'Adil El Alaoui',
    email: 'adil.el@example.com',
    password: 'SecureP@ss123',
    isValid: true,
  },
  {
    name: 'Samira Amrani',
    email: 'samira.a@example.com',
    password: 'MonPwdSecure',
    isValid: true,
  },
  {
    name: 'Yassine Benslimane',
    email: 'yassine.b@example.com',
    password: 'P@ssword789',
    isValid: true,
  },
];
